### ISSUE TITLE
Pull additional season artwork

### ISSUE THREAD

**Issue by pkscout** [pkscout/metadata.tvshows.themoviedb.org.python#10]
Currently only the primary poster image for a season is scraped. Need to pull the URLs for the others so that you can choose a different season poster.

**Comment by pkscout** [comment]
completed with d08c67bb4aca13f0b90a962ed6b8381838701d9e. Since I ended up having to traverse every season to get additional season posters, ac83674aaab0e8efbdec8f433671f07c11658e39 creates the series cast list from the amalgamation of the season cast lists (starting with the most recent season and working backwards).

**Comment by KarellenX** [comment]
For the three tv shows I tested, all season artwork was scraped correctly from TheMovieDB

Thanks!!

**Comment by pkscout** [comment]
Great. Just FYI, I added some enhancements to it to try and deal with episode groupings that have different season numbers than the show as listed in tvdb. All seasons in an episode group now get some kind of artwork, but there is no guarantee it will be useful. Basically tmdb doesn't let you attach artwork to the seasons in an episode grouping, so I use the season artwork from the original season. In some cases people have added posters there that can be used for the alternate season, but not always.  Money Heist is a good example of the challenge (as is the Chilling Adventures of Sabrina).

**Comment by KarellenX** [comment]
Ok, I'll give that a try. Thanks.
