### ISSUE TITLE
Missing data (minor)

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#11]
At the episode level Director and Credits are not being added at the episode level, but they do appear in the API return.

```python
{'air_date': '2018-10-12',
                                     'crew': [{'credit_id': '5da61cb887e63e001739df62',
                                             'department': 'Directing',
                                             'gender': 0,
                                             'id': 2082195,
                                             'job': 'Director',
                                             'name': 'Alexis Ostrander',
                                             'profile_path': None},
                                             {'credit_id': '5da61cca38765100145d5d3e',
                                             'department': 'Writing',
                                             'gender': 2,
                                             'id': 62512,
                                             'job': 'Teleplay',
                                             'name': 'R. Lee Fleming Jr.',
                                             'profile_path': '/pemrMokmTNINhd3hkSRzBwYFvxO.jpg'}],
```

At the TV Show level, Original Title is missing, but I assume that will need to be included as part of the "Keep Original Title" setting.
```python
'original_name': 'Light as a Feather',
```
You would use this, for example, where the show can be commonly known with two different titles eg
**Money Heist**
or 
**La Casa del Papel**
The user can then choose which name to use.

![la-casa](https://user-images.githubusercontent.com/44626605/93729481-f692ae00-fc07-11ea-99c6-b215026bfcdb.jpg)

**Comment by pkscout** [comment]
Oh sure, I just deleted the "Keep Original Title" setting because I had no idea what it was for.  Guess I'll be adding it back.  '-)  As for the writing credits, at the show level I only include people in the "created_by" field in tmdb, but I'm thinking I should include any crew that are in the 'Writing' department too.  At the episode level, I have two questions:

1. For director, should I only include folks with 'Director' as their job, or should I include anyone from the 'Directing' department?
1. Similar to the show level writing credits, I'm thinking anyone in the 'Writing' department should be included in the writing credits at the episode level (that's more of a comment than a question I guess).

**Comment by KarellenX** [comment]
hehe, while you are at it, you need to add one more setting. I'll ping you in the appropriate thread after this post.

1. I searched for types of Director, but I don't think you need to add the others as they belong to different departments. I couldn't find anything else in Directing department apart from Director.
![director](https://user-images.githubusercontent.com/44626605/93731712-930d7e00-fc11-11ea-8b29-bb627e31de7f.JPG)

2. Sounds good to me.

Thanks.

**Comment by pkscout** [comment]
Added option to keep original show title with 2ff6d3cbcb8ace0f763df00b966a7b49a8906d0f.

**Comment by pkscout** [comment]
With 6b352215079468f173acc01d45aacdcddc6cd505 I added writers and directors for episodes. At the show level, I also added writers from the crew to the show writers list (previously only included creators). I can't seem to see the writers or directors anywhere (show or episode level), nor can I find them in the database (although I'm not sure I know where to look). But the logging confirms I am trying to add them. So I definitely need you to check and see if that's behaving as expected.

**Comment by KarellenX** [comment]
Original Show Title setting- Works.

### TV Show
There are no Writers or Directors at the **TV Show** level. There are no fields for either in the database...
https://kodi.wiki/view/Databases/MyVideos#tvshow

### Episodes
Writers and Directors for **episodes** are working. They can be found on the Information Page for each episode...
- Directors are saved in the Actors table. The actor_id is then linked to the episode media_id in the Directors table
https://kodi.wiki/view/Databases/MyVideos#director_link
- Writers are saved in the Actors table (I don't know why though). Writers are also saved in **c04** of the episode table and I think this is from where Kodi gets the writers to display, not the Actors table. 
https://kodi.wiki/view/Databases/MyVideos#episode

![episode](https://user-images.githubusercontent.com/44626605/93840391-9cf7b580-fcd3-11ea-93d8-b1afbb52c67d.jpg)

**Comment by pkscout** [comment]
Good enough. I changed to Estuary and was able to see the episode stuff (Arctic Horizon apparently doesn't show it). The TVMaze scraper tries to do credits at the show level, so I just assumed they worked.  I'll go back and take the code out for writing credits at the show level, but later. I'm going to chalk this up as a win and close the issue.

**Comment by KarellenX** [comment]
Fantastic.

We (ok, you) have a working scraper! It is already good enough to be let loose for wider testing :)

Thank you!!
