### ISSUE TITLE
uniqueID is not provided on seasons and incorrect on episodes

### ISSUE THREAD

**Issue by ReenigneArcher** [pkscout/metadata.tvshows.themoviedb.org.python#119]
I am developing an addon that uses `xbmc.getInfoLabel(f'ListItem.UniqueID(tmdb)')` to get the tmdb of the selected item.

For TV Shows using this scraper, the tmdb is available at the top level show level, but...

- on the season level it is empty
- on the episode level it is incorrect

For example on the episode list of The IT Crowd. I get:

- 189511
- 189512
- 189513
- etc.

But the actual id of the show is `2490`.

This is using v1.6.5.

**Comment by KarellenX** [comment]
>189511
189512
189513

Wouldn't they be the ID for the episodes?
For some reason the TMDB website does not reveal episode id's

As for seasons, we don't save unique IDs.

**Comment by ReenigneArcher** [comment]
> For some reason the TMDB website does not reveal episode id's

My guess would be because it's not needed for any API calls except listing recent changes (https://developer.themoviedb.org/reference/tv-episode-changes-by-id). I think it's really only used internally for editing the database.

Normally all the required ids are part of the URL.

`https://www.themoviedb.org/tv/2490-the-it-crowd/season/3/episode/1`

e.g. The above is a series id of `2490`, season number of `3`, episode number of `1`.

That's all the information you need to make most API calls related to a particular show, season, and episode.

https://developer.themoviedb.org/reference/tv-episode-details

Anyway, other video addons seem to use the tmdb series id as the unique id for the season and episode. I believe that's more valuable than an unused episode id especially since there is no way to determine which show or season an episode id belongs to.

**Comment by KarellenX** [comment]
>other video addons seem to use the tmdb series id as the unique id for the season and episode

Then it's not unique.
It is meant to be exactly what the name implies. Each movie, tv show and episode record in the database needs a uniqueID.

What are you trying to achieve? Have you checked out one of the TMDB helper addons to see how they accomplish it?

**Comment by ReenigneArcher** [comment]
> It is meant to be exactly what the name implies. Each movie, tv show and episode record in the database needs a uniqueID.

I know Kodi has the DBID which needs to be unique. I don't think the uniqueID key for `tmdb`, `imdb` needs to be unique necessarily as these are just properties for the list item.

The current value that this addon provides is not really useful though. No one is using tmdb episode (or season) ids to do lookups in any database because they don't allow it. They intentionally don't allow it because the value is not stable. See:

- https://www.themoviedb.org/talk/552e997ac3a36804cd0013ab
- https://www.themoviedb.org/talk/591220e7c3a36864ec043a46
- https://www.themoviedb.org/talk/6069ddfd124c8d003f3703d2

> Have you checked out one of the TMDB helper addons to see how they accomplish it?

I tried to use The TMDB Helper addon, but it doesn't add properties for existing lists... I did see it creates it's own lists and adds `tmdb_id` as well as `tvshow.tmdb_id` for shows, seasons, and episodes. Maybe I missed something, but that is what I see after looking at the source code and installing it.

> What are you trying to achieve?

I simply need to get the tmdb id of the parent show when a season or episode is selected. My addon relies on the tmdb and/or imdb of the currently selected item.

I use tmdb api quite a bit in various projects (Plex, Jellyfin, etc.), and from my perspective `tmdb id` refers to a movie id or show id. I've not seen any other projects use these season/episode ids.

Perhaps a compromise would be to make the id `showId-seasonNumber-episodeNumber`. E.g. `2490-1-1` This would at least make the id useful, although I still think the uniqueId could be the show's id since the episode and season number can already be obtained through other means (`ListItem.Episode` and `ListItem.Season`)

You can also set other unique ids besides `tmdb`... so could you do `tmdbEpisodeId` and `tmdbSeasonId` as keys for the uniqueIds but have the main one be for the show itself?
