### ISSUE TITLE
Certification Languages not all in alphabetical order

### ISSUE THREAD

**Issue by pkscout** [pkscout/metadata.tvshows.themoviedb.org.python#19]
The "ge" certification language appears to be out of order. Needs to be fixed in settings.

**Comment by KarellenX** [comment]
![certoutoforder](https://user-images.githubusercontent.com/44626605/95276752-cc8feb80-0897-11eb-935c-7bc7af1d1ceb.jpg)

**Comment by pkscout** [comment]
fixed with e0a395b6baacf656e868b3debd2d0fcf20d09ea6 (there is no test build of this available).

**Comment by pkscout** [comment]
I added this change to the Leia branch as well, so this fix will be included in whatever the next release is.
