### ISSUE TITLE
Check unicode issues on logging in Kodi 18

### ISSUE THREAD

**Issue by pkscout** [pkscout/metadata.tvshows.themoviedb.org.python#20]
With debug logging on some of the log data is in unicode, which the Kodi 18 version isn't handling well.

**Comment by KarellenX** [comment]
https://paste.kodi.tv/apilidedux.kodi

**Comment by pkscout** [comment]
This should be fixed with 02e17d7f180588851f294278c1add51b3f88267d.  The issue was an actor (Mathieu Carrière) in Quantum Leap S02E01 with an extended character. This issue won't show up in Matrix and likely wouldn't show up at all on Leia unless you have verbose debug logging on. The fix will be included in the next release.

**Comment by Sauron3019** [comment]
https://paste.kodi.tv/ajujigurer.kodi

**Comment by pkscout** [comment]
@Sauron3019, replying to a closed issue with a link to 5 lines of a log snippet isn't the appropriate way to get support. If you have an issue, I need a link to a complete debug log as well as a description of the issue. I would suggest you open a new issue here or find the correct forum thread and post it there.
