### ISSUE TITLE
Error while scanning

### ISSUE THREAD

**Issue by Sauron3019** [pkscout/metadata.tvshows.themoviedb.org.python#24]
https://paste.kodi.tv/iyudodufij.kodi

**Comment by pkscout** [comment]
That is not a debug log. You MUST turn debugging on in Kodi, duplicate the problem, and post a link to the log.

**Comment by Sauron3019** [comment]
https://paste.kodi.tv/muzixisinu.kodi

**Comment by pkscout** [comment]
That issue should be resolved with 1.1.9.  I confirmed by scraping the same show in your log (Daredevil). That hasn't been released yet, but you can get a zip of it from the Leia branch of this repo and then install it from the zip file.

**Comment by Sauron3019** [comment]
https://paste.kodi.tv/buliworuse.kodi

**Comment by Sauron3019** [comment]
https://paste.kodi.tv/icoweziyax.kodi

**Comment by Sauron3019** [comment]
Season 1 episode names are missing.

![(24)](https://user-images.githubusercontent.com/66399617/99299973-0d96fa80-285d-11eb-8c4f-0ae3bddbed26.png)

https://paste.kodi.tv/ozalowatad.kodi

**Comment by pkscout** [comment]
This latest log has nothing to do with your original issue. I really do want to help, but posting random logs in closed issues is not making it easy. I will take a look, but in the future please open a new issue and describe your issue in detail.
