### ISSUE TITLE
Add ability to find show with external ID

### ISSUE THREAD

**Issue by pkscout** [pkscout/metadata.tvshows.themoviedb.org.python#3]
see https://developers.themoviedb.org/3/getting-started/external-ids

**Comment by KarellenX** [comment]
Might be of help...
https://github.com/xbmc/metadata.themoviedb.org.python/pull/15

**Comment by pkscout** [comment]
I'm going to close this one undone. I was looking at the find method again (which is a separate way to look for things using external IDs), and I'm not sure I want to do a search that way for a TV show. The movie scraper seems to have implemented it as an option during manual searches, which I think is of limited value. I had thought about using it to look at old parsing URLs that may have been left in directories,  but I don't think it would save any API calls to try and use that. If there is a large desire for this, I'll look at adding it later.

**Comment by KarellenX** [comment]
For future reference.

The reason that some users would find it useful is for failed scrapes. It allows the user to use another method to find the correct tv show rather than forcing a user to create a Parsing NFO file outside of Kodi, which some users will find difficult.

This is not meant to work at the episode level.

![search1](https://user-images.githubusercontent.com/44626605/93658986-e0f47b80-fa83-11ea-8e7b-e2956dc3d7f1.jpg)


![search2](https://user-images.githubusercontent.com/44626605/93658984-de922180-fa83-11ea-9823-e2921d6e1159.jpg)

**Comment by pkscout** [comment]
OK, I guess I get it now. I'll reopen this.

**Comment by pkscout** [comment]
added with 955d5a2d42e89db7c27e56116d96e1d0ee85ce62. This uses the same formatting requirements as the tmdb movie scraper. Manual TVDB ID searches must be start with `tvdb/` (i.e. `tvdb/369950`).  IMDB IDs can either be alone (`tt8210856`) or start with `imdb/` (i.e `imdb/tt8210856`).

**Comment by KarellenX** [comment]
Thanks, That seems to have fixed the non-unique issue.

**Comment by KarellenX** [comment]
Tested and no issues found. Is it possible to add the ability to search by **tmdb/** also?

**Comment by pkscout** [comment]
I should be able to add tmdb/ as well, but the API call for searching by external ID is different than getting a show with the tvdb_id, so there's a little logic puzzle I have to figure out first.

**Comment by KarellenX** [comment]
Thanks. Does rmrectos implementation I linked above help solve the puzzle?

**Comment by pkscout** [comment]
Unfortunately, no. I quit using tvdbsimple because it was causing me other headaches (it has like 98% of the API, but the 2% it doesn't have really hurts for me), and it looks like tvdbsimple bundles up some of the search routines into one interface and figures out which one to use.  I'm pretty sure I know what I need to do, I just need some time to think it through and then try it.

**Comment by pkscout** [comment]
With 44a639081d35bcb7ec1fae1200f53968913497f1 you can now search using tmdb_id by starting the manual search with `tmdb/`.

**Comment by KarellenX** [comment]
**tmdb/123456** works as expected.

Thanks!!
