### ISSUE TITLE
Extended Artwork- fanart.tv

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#4]
The scraper already downloads Poster and Fanart for TV Shows.

Could you also add scraping of extended artwork from fanart.tv? This would include

TV Show
-  banner
-  characterart
-  clearart
-  clearlogo
-  landscape

Season
-  season landscape
-  season banner.

Something similar to this...

![fanart tv](https://user-images.githubusercontent.com/44626605/93049737-f55fff00-f6a4-11ea-8065-37bb52b0fd04.jpg)

**Comment by pkscout** [comment]
With dd8b497c67c952dd01dea74757e3fcadacd28fa8 I have added fanart and posters from fanart.tv at the show level. You need to enable them in the settings.  I went ahead and added the rest of the settings for the different artwork, and hopefully I can get to those this coming week.  BTW, don't get too excited about the settings for the ratings.  I decided to go ahead and get the settings done so I didn't have to keep editing them, but I don't have an ETA for the extra ratings yet.  '-)

**Comment by KarellenX** [comment]
A few more settings...
**Season Landscape** which is listed as **Season Thumbs** at fanart.tv
**Landscape** which is listed as **TVThumbs** at fanart.tv
**Characterart**

https://fanart.tv/series/327417/la-casa-de-papel/

**Comment by pkscout** [comment]
With f83e153d6e071eb1bbd64ed5f4f14b540af2a6c7 the scraper now loads all artwork types (if enabled) at the show level from fanart.tv.  f83e153d6e071eb1bbd64ed5f4f14b540af2a6c7 adds the same support for seasons. There are currently no limits on the number of images, so if every artwork type is enabled there is a chance the list of images will be longer than can be stored in Kodi.  I have started another issue for limiting the number of images at https://github.com/pkscout/metadata.tvshows.themoviedb.org.python/issues/12

**Comment by KarellenX** [comment]
Thanks @pkscout I tested three popular shows and it all seems to be working. :-)
