### ISSUE TITLE
[Nexus v20] Missing UniqueID from tvshow

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#68]
Kodi v20 using TMDB TV Shows v1.4.10

The IMDB and TVDB UniqueID's are not scraped. Only the TMDB ID is added to the tvshow. I noticed this when the WatchedList addon failed to work due to the missing TVDB ID.

Episodes have the three UniqueID's scraped, so no problems there.

The log has a number of warnings as follows, although I do not think it is the immediate cause of the above problem...
`ListItem.setUniqueIDs() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setUniqueIDs()`

There are other similar warnings in the log...
`ListItem.addSeason() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addSeason().`
`ListItem.setCast() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setCast().`
`ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().`

Log... https://paste.kodi.tv/exihurafiv.kodi

**Comment by pkscout** [comment]
I did a test scrape of V (2009) on my Matrix test setup, and it does get all three IDs using 1.4.10.  I guess something has changed with Nexus, so I'm going to have to do some investigation to figure out what.  Those warnings must be related to calls that have been depreciated as of Nexus, so I'll have to check into that too.

**Comment by pkscout** [comment]
Just noting this GitHub comment on the changes to the Python libraries.

https://github.com/xbmc/xbmc/pull/19459#issuecomment-806450382

I still need to look to see if these changes are in a matrix or if I need to plan on a Nexus specific version (or code logic to call the right thing).

**Comment by pkscout** [comment]
This is just to confirm that in Nexus the current scraper apparently only saves the TMDb ID.  It probably has to do with the changes to how video info should be set.  I'm starting work on a Nexus specific version of the scraper that will use the new Python bindings for setting video info.

**Comment by KarellenX** [comment]
Thanks @pkscout 
Let me know if you need some testing

**Comment by pkscout** [comment]
This should be fixed in the beta I just posted in the Nexus branch.  I also changed all the setters to use the new Nexus ones, so you shouldn't get any more depreciation messages when scanning for TV shows using this scraper.

**Comment by pkscout** [comment]
Fixed for Nexus with 53bba3a9235895c6cea44684da42b967b7316b1c and cae1148ec6d33a5bec2e65a798b6ff48020c1e0d.  Pushing this to the Nexus repo so that it can be included in Alpha1.
