### ISSUE TITLE
Ratings & Votes

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#7]
There are no ratings or votes for episodes being scraped.

In addition to TheMovieDB ratings and votes for TV Shows, is it possible to add IMDB Ratings and votes, and also add both for episodes?

Maybe @razzeee might be able to help with Trakt ratings and votes? https://github.com/xbmc/metadata.themoviedb.org.python/pull/9

**Comment by pkscout** [comment]
Hmmm. The code is loading the vote average from tmdb. I need to see if the skin I'm using will show stuff like that to test. I'll add ratings from other sites to the list of enhancement requests.

**Comment by pkscout** [comment]
OK, I see now. There are two things. I'm loading tmdb vote average (i.e. the rating) for the show, not the episode. I need to add vote average to episodes and vote numbers for both. They are loaded in with themoviedb as a type, so unless I label them as default, they'll only show if a skin supports them.  Votes/ratings from other services is possible, but I'm holding off on any work that requires another site API until I finish everything that can be done just within tmdb.

**Comment by pkscout** [comment]
Ratings and vote counts for shows and episodes are now set from tmdb only. I haven't started looking at the other site APIs yet.

**Comment by KarellenX** [comment]
A heads up in case you were considering adding TVDB ratings. Don't! :)

TVDB deprecated ratings and votes on their site when they switched to their new website almost a year ago. I have asked both olympia and razzee to remove tvdb ratings from their scrapers but they have not done so to date.

TVDB ratings are still available up until the time the new website became active, so historical ratings are available but are outdated and stale. New shows added to the site or broadcast since the website switchover have no ratings at all.

https://github.com/xbmc/metadata.tvdb.com.python/issues/16

**Comment by KarellenX** [comment]
I noticed that v1.1.5 has removed the rating settings. Are they coming back?

**Comment by pkscout** [comment]
They are. For wider testing I didn't want people giving me feedback that the ratings weren't working. And tmdb ratings are still loaded, there's just no setting to change it for right now.

**Comment by KarellenX** [comment]
Yep, makes sense. Thanks.

**Comment by pkscout** [comment]
Trackt and IMDb ratings for shows and episodes are now available as an option as of v.1.1.9,. I'll leave this open just until we confirm it is working as expected.

**Comment by pkscout** [comment]
I have a new test version of the Trakt ratings that uses just a couple direct API calls to Trakt. I think that will eliminate the possibility of the tzinfo bug, as I'm not using any date stuff (which I think happened by default when using the trakt python wrapper before). I rescanned my entire TV show library on my Mac with Trakt ratings on and didn't run into any issues. When you get some time, could you check too? You can get the test version from https://github.com/pkscout/metadata.tvshows.themoviedb.org.python/tree/feature-new-trakt

**Comment by KarellenX** [comment]
Sure. I will a bit later. Have to pop out for a while. 

Thanks!!

**Comment by KarellenX** [comment]
I tested the two shows that caused the problem last time, and two other shows.

No problems with tzinfo, no crashing. All worked well.

Trakt ratings were scraped. I don't have a trakt account so could not double check ratings, but the right number of episodes -v-ratings were scraped along with IMDB and TMDB.

Thanks @pkscout  :)

**Comment by pkscout** [comment]
Great. I'll push this update out yet today. I'm going to go ahead and close this.
