### ISSUE TITLE
Episode Thumbs

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#9]
Currently the scraper only scrapes the first (or highest rated) image for episodes.

Using Choose Art, there are no available episode thumbs to choose from, except the currently displayed one, even though multiple episode artwork exists at TheMovieDB as shown in the image. This makes it difficult for users to change a bad quality image for a better one.

Could you scrape the links for all available artwork for episodes?

![episodethumbs](https://user-images.githubusercontent.com/44626605/93052286-2cd0aa80-f6a9-11ea-989c-d061951aaf40.JPG)

**Comment by pkscout** [comment]
complete via 13fafa49b3cff7ad49ede3d65d5cab7d9030e890 and 433898b7149810d62442091cf80150d8ae037fef. These changes have been pushed to the main branch.
